[workspace]
resolver = "3"
members = ["benchmark", "common", "problem-a", "problem-b"]

[workspace.metadata.problem-b]
start_time = 2025-09-05T16:28:17.527055
completion_time = 2025-09-05T17:13:53.229621
