[package]
name = "problem-l"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { version = "0.1.0", path = "../common" }
indicatif = { version = "0.18.0", features = ["rayon"] }
rayon = "1.11.0"
